/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author happy
 */
public class MainApplicationForm extends javax.swing.JFrame {

    /**
     * Creates new form MainApplicationForm
     */
    public MainApplicationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        productMenu = new javax.swing.JMenu();
        AddProductMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        CustomerMenuItem = new javax.swing.JMenuItem();
        AddEmployeeMenuItem = new javax.swing.JMenu();
        AddEmployeeMenu = new javax.swing.JMenuItem();
        rentalGUI = new javax.swing.JMenu();
        rentMenuItem = new javax.swing.JMenuItem();
        searchProductByDateMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(813, 705));

        mainDesktopPane.setPreferredSize(new java.awt.Dimension(863, 801));

        javax.swing.GroupLayout mainDesktopPaneLayout = new javax.swing.GroupLayout(mainDesktopPane);
        mainDesktopPane.setLayout(mainDesktopPaneLayout);
        mainDesktopPaneLayout.setHorizontalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        mainDesktopPaneLayout.setVerticalGroup(
            mainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        productMenu.setText("Product");
        productMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productMenuActionPerformed(evt);
            }
        });

        AddProductMenu.setText("Add Product");
        AddProductMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductMenuActionPerformed(evt);
            }
        });
        productMenu.add(AddProductMenu);
        productMenu.add(jSeparator1);

        jMenuBar1.add(productMenu);

        jMenu2.setText("Customer");

        CustomerMenuItem.setText("Add Customer");
        CustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(CustomerMenuItem);

        jMenuBar1.add(jMenu2);

        AddEmployeeMenuItem.setText("Employee");

        AddEmployeeMenu.setText("Add Employee");
        AddEmployeeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeMenuActionPerformed(evt);
            }
        });
        AddEmployeeMenuItem.add(AddEmployeeMenu);

        jMenuBar1.add(AddEmployeeMenuItem);

        rentalGUI.setText("Rental");

        rentMenuItem.setText("Rent/Return");
        rentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentMenuItemActionPerformed(evt);
            }
        });
        rentalGUI.add(rentMenuItem);

        searchProductByDateMenuItem.setText("Search Product by Date");
        searchProductByDateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductByDateMenuItemActionPerformed(evt);
            }
        });
        rentalGUI.add(searchProductByDateMenuItem);

        jMenuBar1.add(rentalGUI);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddProductMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductMenuActionPerformed
        // TODO add your handling code here:
                mainDesktopPane.removeAll();
                ProductIF form = new ProductIF();
                mainDesktopPane.add(form).setVisible(true);
    }//GEN-LAST:event_AddProductMenuActionPerformed

    private void productMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productMenuActionPerformed
        // TODO add your handling code here:
                
    }//GEN-LAST:event_productMenuActionPerformed

    private void CustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMenuItemActionPerformed
        // TODO add your handling code here:
                mainDesktopPane.removeAll();
                CustomerIF form = new CustomerIF();
                mainDesktopPane.add(form).setVisible(true);
    }//GEN-LAST:event_CustomerMenuItemActionPerformed

    private void AddEmployeeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeMenuActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_AddEmployeeMenuActionPerformed

    private void rentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentMenuItemActionPerformed
        // TODO add your handling code here:
                mainDesktopPane.removeAll();
                RentalRecordIF form = new RentalRecordIF();
                mainDesktopPane.add(form).setVisible(true);
    }//GEN-LAST:event_rentMenuItemActionPerformed

    private void searchProductByDateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductByDateMenuItemActionPerformed
        // TODO add your handling code here:
                mainDesktopPane.removeAll();
                SearchProductByDateIF form = new SearchProductByDateIF();
                mainDesktopPane.add(form).setVisible(true);
    }//GEN-LAST:event_searchProductByDateMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApplicationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApplicationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddEmployeeMenu;
    private javax.swing.JMenu AddEmployeeMenuItem;
    private javax.swing.JMenuItem AddProductMenu;
    private javax.swing.JMenuItem CustomerMenuItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane mainDesktopPane;
    private javax.swing.JMenu productMenu;
    private javax.swing.JMenuItem rentMenuItem;
    private javax.swing.JMenu rentalGUI;
    private javax.swing.JMenuItem searchProductByDateMenuItem;
    // End of variables declaration//GEN-END:variables
}
