/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.DataStore;
import Stockmanagement.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author happy
 */
public class ProductIF extends javax.swing.JInternalFrame {
DataStore dataStore = new DataStore();
    /**
     * Creates new form ProductIF
     */
    public ProductIF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProductButton = new javax.swing.JButton();
        rentTextField = new javax.swing.JTextField();
        idLable = new javax.swing.JLabel();
        rentLable = new javax.swing.JLabel();
        rentLable1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        colourTextField = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        addProductButton1 = new javax.swing.JButton();
        modelLable1 = new javax.swing.JLabel();
        modelTextField1 = new javax.swing.JTextField();
        idLable1 = new javax.swing.JLabel();
        rentLable2 = new javax.swing.JLabel();
        rentPerDayTextField1 = new javax.swing.JTextField();
        statusTextField1 = new javax.swing.JTextField();
        rentLable3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productNameTextField1 = new javax.swing.JTextField();
        idTextField1 = new javax.swing.JTextField();
        serialTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        idLable2 = new javax.swing.JLabel();
        idLable3 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        addProductButton2 = new javax.swing.JButton();
        modelLable2 = new javax.swing.JLabel();
        modelTextField2 = new javax.swing.JTextField();
        idLable4 = new javax.swing.JLabel();
        rentLable4 = new javax.swing.JLabel();
        rentPerDayTextField2 = new javax.swing.JTextField();
        statusTextField2 = new javax.swing.JTextField();
        rentLable5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productNameTextField3 = new javax.swing.JTextField();
        idTextField3 = new javax.swing.JTextField();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        addProductButton3 = new javax.swing.JButton();
        modelLable3 = new javax.swing.JLabel();
        modelTextField3 = new javax.swing.JTextField();
        idLable5 = new javax.swing.JLabel();
        rentLable6 = new javax.swing.JLabel();
        rentPerDayTextField3 = new javax.swing.JTextField();
        statusTextField3 = new javax.swing.JTextField();
        rentLable7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        productNameTextField4 = new javax.swing.JTextField();
        idTextField4 = new javax.swing.JTextField();
        productNameTextField5 = new javax.swing.JTextField();
        idTextField5 = new javax.swing.JTextField();
        idLable6 = new javax.swing.JLabel();
        idLable7 = new javax.swing.JLabel();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        addProductButton4 = new javax.swing.JButton();
        modelLable4 = new javax.swing.JLabel();
        modelTextField4 = new javax.swing.JTextField();
        idLable8 = new javax.swing.JLabel();
        rentLable8 = new javax.swing.JLabel();
        rentPerDayTextField4 = new javax.swing.JTextField();
        statusTextField4 = new javax.swing.JTextField();
        rentLable9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        productNameTextField6 = new javax.swing.JTextField();
        idTextField6 = new javax.swing.JTextField();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        addProductButton5 = new javax.swing.JButton();
        modelLable5 = new javax.swing.JLabel();
        modelTextField5 = new javax.swing.JTextField();
        idLable9 = new javax.swing.JLabel();
        rentLable10 = new javax.swing.JLabel();
        rentPerDayTextField5 = new javax.swing.JTextField();
        statusTextField5 = new javax.swing.JTextField();
        rentLable11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        productNameTextField7 = new javax.swing.JTextField();
        idTextField7 = new javax.swing.JTextField();
        productNameTextField8 = new javax.swing.JTextField();
        idTextField8 = new javax.swing.JTextField();
        idLable10 = new javax.swing.JLabel();
        idLable11 = new javax.swing.JLabel();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        addProductButton6 = new javax.swing.JButton();
        modelLable6 = new javax.swing.JLabel();
        modelTextField6 = new javax.swing.JTextField();
        idLable12 = new javax.swing.JLabel();
        rentLable12 = new javax.swing.JLabel();
        rentPerDayTextField6 = new javax.swing.JTextField();
        statusTextField6 = new javax.swing.JTextField();
        rentLable13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        productNameTextField9 = new javax.swing.JTextField();
        idTextField9 = new javax.swing.JTextField();
        jInternalFrame7 = new javax.swing.JInternalFrame();
        addProductButton7 = new javax.swing.JButton();
        modelLable7 = new javax.swing.JLabel();
        modelTextField7 = new javax.swing.JTextField();
        idLable13 = new javax.swing.JLabel();
        rentLable14 = new javax.swing.JLabel();
        rentPerDayTextField7 = new javax.swing.JTextField();
        statusTextField7 = new javax.swing.JTextField();
        rentLable15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        productNameTextField10 = new javax.swing.JTextField();
        idTextField10 = new javax.swing.JTextField();
        productNameTextField11 = new javax.swing.JTextField();
        idTextField11 = new javax.swing.JTextField();
        idLable14 = new javax.swing.JLabel();
        idLable15 = new javax.swing.JLabel();
        leghtTextField = new javax.swing.JTextField();
        heightTextField = new javax.swing.JTextField();
        widthTextField = new javax.swing.JTextField();
        idLable16 = new javax.swing.JLabel();
        idLable17 = new javax.swing.JLabel();
        idLable18 = new javax.swing.JLabel();
        productStatusComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        guitarComboBox = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1250, 950));

        addProductButton.setText("add");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        rentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentTextFieldActionPerformed(evt);
            }
        });

        idLable.setText("Serial Number");

        rentLable.setText("RentPerDay");

        rentLable1.setText("Status");

        jLabel1.setText("name");

        colourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourTextFieldActionPerformed(evt);
            }
        });

        jInternalFrame1.setPreferredSize(new java.awt.Dimension(813, 734));

        addProductButton1.setText("add");
        addProductButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButton1ActionPerformed(evt);
            }
        });

        modelLable1.setText("model");

        modelTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextField1ActionPerformed(evt);
            }
        });

        idLable1.setText("id");

        rentLable2.setText("RentPerDay");

        rentPerDayTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPerDayTextField1ActionPerformed(evt);
            }
        });

        statusTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextField1ActionPerformed(evt);
            }
        });

        rentLable3.setText("Status");

        jLabel2.setText("name");

        productNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField1ActionPerformed(evt);
            }
        });

        idTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(idLable1)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(rentLable3))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rentLable2))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(modelLable1)))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField1)
                        .addComponent(addProductButton1)
                        .addComponent(statusTextField1)
                        .addComponent(modelTextField1)
                        .addComponent(productNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rentPerDayTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(idLable1)
                .addGap(55, 55, 55)
                .addComponent(productNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLable1))
                .addGap(18, 18, 18)
                .addComponent(modelTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentPerDayTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable3))
                .addGap(18, 18, 18)
                .addComponent(addProductButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        serialTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialTextFieldActionPerformed(evt);
            }
        });

        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        idLable2.setText("Year Manuf.");

        idLable3.setText("Colour");

        jInternalFrame2.setPreferredSize(new java.awt.Dimension(813, 734));

        addProductButton2.setText("add");
        addProductButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButton2ActionPerformed(evt);
            }
        });

        modelLable2.setText("model");

        modelTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextField2ActionPerformed(evt);
            }
        });

        idLable4.setText("Serial Number");

        rentLable4.setText("RentPerDay");

        rentPerDayTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPerDayTextField2ActionPerformed(evt);
            }
        });

        statusTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextField2ActionPerformed(evt);
            }
        });

        rentLable5.setText("Status");

        jLabel3.setText("name");

        productNameTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField3ActionPerformed(evt);
            }
        });

        idTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField3ActionPerformed(evt);
            }
        });

        jInternalFrame3.setPreferredSize(new java.awt.Dimension(813, 734));

        addProductButton3.setText("add");
        addProductButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButton3ActionPerformed(evt);
            }
        });

        modelLable3.setText("model");

        modelTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextField3ActionPerformed(evt);
            }
        });

        idLable5.setText("id");

        rentLable6.setText("RentPerDay");

        rentPerDayTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPerDayTextField3ActionPerformed(evt);
            }
        });

        statusTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextField3ActionPerformed(evt);
            }
        });

        rentLable7.setText("Status");

        jLabel4.setText("name");

        productNameTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField4ActionPerformed(evt);
            }
        });

        idTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(idLable5)))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(rentLable7))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rentLable6))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(modelLable3)))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField4)
                        .addComponent(addProductButton3)
                        .addComponent(statusTextField3)
                        .addComponent(modelTextField3)
                        .addComponent(productNameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rentPerDayTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(idLable5)
                .addGap(55, 55, 55)
                .addComponent(productNameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLable3))
                .addGap(18, 18, 18)
                .addComponent(modelTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentPerDayTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable7))
                .addGap(18, 18, 18)
                .addComponent(addProductButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productNameTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField5ActionPerformed(evt);
            }
        });

        idTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField5ActionPerformed(evt);
            }
        });

        idLable6.setText("Year Manuf.");

        idLable7.setText("Colour");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(idLable4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLable6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLable5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLable4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modelLable2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField5)
                        .addComponent(productNameTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField3)
                        .addComponent(addProductButton2)
                        .addComponent(statusTextField2)
                        .addComponent(modelTextField2)
                        .addComponent(productNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rentPerDayTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame2Layout.createSequentialGroup()
                    .addGap(0, 111, Short.MAX_VALUE)
                    .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 112, Short.MAX_VALUE)))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable6))
                .addGap(111, 111, 111)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLable2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentPerDayTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable5))
                .addGap(18, 18, 18)
                .addComponent(addProductButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame2Layout.createSequentialGroup()
                    .addGap(0, 202, Short.MAX_VALUE)
                    .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 203, Short.MAX_VALUE)))
        );

        jInternalFrame4.setPreferredSize(new java.awt.Dimension(813, 734));

        addProductButton4.setText("add");
        addProductButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButton4ActionPerformed(evt);
            }
        });

        modelLable4.setText("model");

        modelTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextField4ActionPerformed(evt);
            }
        });

        idLable8.setText("Serial Number");

        rentLable8.setText("RentPerDay");

        rentPerDayTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPerDayTextField4ActionPerformed(evt);
            }
        });

        statusTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextField4ActionPerformed(evt);
            }
        });

        rentLable9.setText("Status");

        jLabel5.setText("name");

        productNameTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField6ActionPerformed(evt);
            }
        });

        idTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField6ActionPerformed(evt);
            }
        });

        jInternalFrame5.setPreferredSize(new java.awt.Dimension(813, 734));

        addProductButton5.setText("add");
        addProductButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButton5ActionPerformed(evt);
            }
        });

        modelLable5.setText("model");

        modelTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextField5ActionPerformed(evt);
            }
        });

        idLable9.setText("id");

        rentLable10.setText("RentPerDay");

        rentPerDayTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPerDayTextField5ActionPerformed(evt);
            }
        });

        statusTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextField5ActionPerformed(evt);
            }
        });

        rentLable11.setText("Status");

        jLabel6.setText("name");

        productNameTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField7ActionPerformed(evt);
            }
        });

        idTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame5Layout = new javax.swing.GroupLayout(jInternalFrame5.getContentPane());
        jInternalFrame5.getContentPane().setLayout(jInternalFrame5Layout);
        jInternalFrame5Layout.setHorizontalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(idLable9)))
                    .addGroup(jInternalFrame5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(rentLable11))
                    .addGroup(jInternalFrame5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rentLable10))
                    .addGroup(jInternalFrame5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(modelLable5)))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField7)
                        .addComponent(addProductButton5)
                        .addComponent(statusTextField5)
                        .addComponent(modelTextField5)
                        .addComponent(productNameTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rentPerDayTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame5Layout.setVerticalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addComponent(idLable9)
                .addGap(55, 55, 55)
                .addComponent(productNameTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLable5))
                .addGap(18, 18, 18)
                .addComponent(modelTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentPerDayTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable11))
                .addGap(18, 18, 18)
                .addComponent(addProductButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productNameTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField8ActionPerformed(evt);
            }
        });

        idTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField8ActionPerformed(evt);
            }
        });

        idLable10.setText("Year Manuf.");

        idLable11.setText("Colour");

        jInternalFrame6.setPreferredSize(new java.awt.Dimension(813, 734));

        addProductButton6.setText("add");
        addProductButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButton6ActionPerformed(evt);
            }
        });

        modelLable6.setText("model");

        modelTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextField6ActionPerformed(evt);
            }
        });

        idLable12.setText("Serial Number");

        rentLable12.setText("RentPerDay");

        rentPerDayTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPerDayTextField6ActionPerformed(evt);
            }
        });

        statusTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextField6ActionPerformed(evt);
            }
        });

        rentLable13.setText("Status");

        jLabel7.setText("name");

        productNameTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField9ActionPerformed(evt);
            }
        });

        idTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField9ActionPerformed(evt);
            }
        });

        jInternalFrame7.setPreferredSize(new java.awt.Dimension(813, 734));

        addProductButton7.setText("add");
        addProductButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButton7ActionPerformed(evt);
            }
        });

        modelLable7.setText("model");

        modelTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextField7ActionPerformed(evt);
            }
        });

        idLable13.setText("id");

        rentLable14.setText("RentPerDay");

        rentPerDayTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentPerDayTextField7ActionPerformed(evt);
            }
        });

        statusTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextField7ActionPerformed(evt);
            }
        });

        rentLable15.setText("Status");

        jLabel8.setText("name");

        productNameTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField10ActionPerformed(evt);
            }
        });

        idTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame7Layout = new javax.swing.GroupLayout(jInternalFrame7.getContentPane());
        jInternalFrame7.getContentPane().setLayout(jInternalFrame7Layout);
        jInternalFrame7Layout.setHorizontalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(idLable13)))
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(rentLable15))
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rentLable14))
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(modelLable7)))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField10)
                        .addComponent(addProductButton7)
                        .addComponent(statusTextField7)
                        .addComponent(modelTextField7)
                        .addComponent(productNameTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rentPerDayTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame7Layout.setVerticalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(15, 15, 15)
                .addComponent(idLable13)
                .addGap(55, 55, 55)
                .addComponent(productNameTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTextField10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLable7))
                .addGap(18, 18, 18)
                .addComponent(modelTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentPerDayTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable15))
                .addGap(18, 18, 18)
                .addComponent(addProductButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productNameTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextField11ActionPerformed(evt);
            }
        });

        idTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField11ActionPerformed(evt);
            }
        });

        idLable14.setText("Year Manuf.");

        idLable15.setText("Colour");

        javax.swing.GroupLayout jInternalFrame6Layout = new javax.swing.GroupLayout(jInternalFrame6.getContentPane());
        jInternalFrame6.getContentPane().setLayout(jInternalFrame6Layout);
        jInternalFrame6Layout.setHorizontalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7))
                    .addGroup(jInternalFrame6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(idLable12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLable14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLable13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLable12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modelLable6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField11)
                        .addComponent(productNameTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField9)
                        .addComponent(addProductButton6)
                        .addComponent(statusTextField6)
                        .addComponent(modelTextField6)
                        .addComponent(productNameTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rentPerDayTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame6Layout.createSequentialGroup()
                    .addGap(0, 111, Short.MAX_VALUE)
                    .addComponent(jInternalFrame7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 112, Short.MAX_VALUE)))
        );
        jInternalFrame6Layout.setVerticalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable14))
                .addGap(111, 111, 111)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLable6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentPerDayTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable13))
                .addGap(18, 18, 18)
                .addComponent(addProductButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame6Layout.createSequentialGroup()
                    .addGap(0, 202, Short.MAX_VALUE)
                    .addComponent(jInternalFrame7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 203, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(idLable8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLable10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLable9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLable8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modelLable4, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField8)
                        .addComponent(productNameTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idTextField6)
                        .addComponent(addProductButton4)
                        .addComponent(statusTextField4)
                        .addComponent(modelTextField4)
                        .addComponent(productNameTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rentPerDayTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                    .addContainerGap(398, Short.MAX_VALUE)
                    .addComponent(jInternalFrame6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable10))
                .addGap(111, 111, 111)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelLable4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rentPerDayTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable9))
                .addGap(18, 18, 18)
                .addComponent(addProductButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                    .addContainerGap(352, Short.MAX_VALUE)
                    .addComponent(jInternalFrame6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(352, Short.MAX_VALUE)))
        );

        leghtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leghtTextFieldActionPerformed(evt);
            }
        });

        heightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextFieldActionPerformed(evt);
            }
        });

        widthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthTextFieldActionPerformed(evt);
            }
        });

        idLable16.setText("Lenght");

        idLable17.setText("Height");

        idLable18.setText("Width");

        productStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available" }));

        jLabel9.setText("Guitar Type");

        guitarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACOUSTIC ", "ELECTRIC" }));
        guitarComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guitarComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLable, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLable, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLable16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rentLable1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yearTextField)
                    .addComponent(serialTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(addProductButton)
                    .addComponent(rentTextField)
                    .addComponent(colourTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(leghtTextField)
                    .addComponent(widthTextField)
                    .addComponent(heightTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(guitarComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productStatusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 973, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(398, Short.MAX_VALUE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLable17)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leghtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(guitarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentLable1)
                    .addComponent(productStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(addProductButton)
                .addContainerGap(542, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(352, Short.MAX_VALUE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(352, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        // TODO add your handling code here:
        String colour=colourTextField.getText();
        String productserial=serialTextField.getText();
        int year=Integer.parseInt(yearTextField.getText());
        double height = Double.parseDouble(heightTextField.getText());
        double width = Double.parseDouble(widthTextField.getText());
        double length = Double.parseDouble(leghtTextField.getText());
        double rent=Double.parseDouble(rentTextField.getText());
        String status = productStatusComboBox.getSelectedItem().toString();
        String type = guitarComboBox.getSelectedItem().toString();
       
        Product p=new Product(productserial,year,rent,colour,length,width,height,status,type);
        dataStore.setProduct(p);
        JOptionPane.showMessageDialog(this,"product added successfully");
      

    }//GEN-LAST:event_addProductButtonActionPerformed

    private void rentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentTextFieldActionPerformed

    private void colourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colourTextFieldActionPerformed

    private void addProductButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductButton1ActionPerformed

    private void modelTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextField1ActionPerformed

    private void rentPerDayTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPerDayTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentPerDayTextField1ActionPerformed

    private void statusTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextField1ActionPerformed

    private void productNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField1ActionPerformed

    private void idTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField1ActionPerformed

    private void serialTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void addProductButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductButton2ActionPerformed

    private void modelTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextField2ActionPerformed

    private void rentPerDayTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPerDayTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentPerDayTextField2ActionPerformed

    private void statusTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextField2ActionPerformed

    private void productNameTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField3ActionPerformed

    private void idTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField3ActionPerformed

    private void addProductButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductButton3ActionPerformed

    private void modelTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextField3ActionPerformed

    private void rentPerDayTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPerDayTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentPerDayTextField3ActionPerformed

    private void statusTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextField3ActionPerformed

    private void productNameTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField4ActionPerformed

    private void idTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField4ActionPerformed

    private void productNameTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField5ActionPerformed

    private void idTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField5ActionPerformed

    private void addProductButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductButton4ActionPerformed

    private void modelTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextField4ActionPerformed

    private void rentPerDayTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPerDayTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentPerDayTextField4ActionPerformed

    private void statusTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextField4ActionPerformed

    private void productNameTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField6ActionPerformed

    private void idTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField6ActionPerformed

    private void addProductButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductButton5ActionPerformed

    private void modelTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextField5ActionPerformed

    private void rentPerDayTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPerDayTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentPerDayTextField5ActionPerformed

    private void statusTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextField5ActionPerformed

    private void productNameTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField7ActionPerformed

    private void idTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField7ActionPerformed

    private void productNameTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField8ActionPerformed

    private void idTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField8ActionPerformed

    private void addProductButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductButton6ActionPerformed

    private void modelTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextField6ActionPerformed

    private void rentPerDayTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPerDayTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentPerDayTextField6ActionPerformed

    private void statusTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextField6ActionPerformed

    private void productNameTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField9ActionPerformed

    private void idTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField9ActionPerformed

    private void addProductButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductButton7ActionPerformed

    private void modelTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextField7ActionPerformed

    private void rentPerDayTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentPerDayTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentPerDayTextField7ActionPerformed

    private void statusTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextField7ActionPerformed

    private void productNameTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField10ActionPerformed

    private void idTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField10ActionPerformed

    private void productNameTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextField11ActionPerformed

    private void idTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField11ActionPerformed

    private void leghtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leghtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leghtTextFieldActionPerformed

    private void heightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextFieldActionPerformed

    private void widthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widthTextFieldActionPerformed

    private void guitarComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guitarComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guitarComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton addProductButton1;
    private javax.swing.JButton addProductButton2;
    private javax.swing.JButton addProductButton3;
    private javax.swing.JButton addProductButton4;
    private javax.swing.JButton addProductButton5;
    private javax.swing.JButton addProductButton6;
    private javax.swing.JButton addProductButton7;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JComboBox<String> guitarComboBox;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel idLable;
    private javax.swing.JLabel idLable1;
    private javax.swing.JLabel idLable10;
    private javax.swing.JLabel idLable11;
    private javax.swing.JLabel idLable12;
    private javax.swing.JLabel idLable13;
    private javax.swing.JLabel idLable14;
    private javax.swing.JLabel idLable15;
    private javax.swing.JLabel idLable16;
    private javax.swing.JLabel idLable17;
    private javax.swing.JLabel idLable18;
    private javax.swing.JLabel idLable2;
    private javax.swing.JLabel idLable3;
    private javax.swing.JLabel idLable4;
    private javax.swing.JLabel idLable5;
    private javax.swing.JLabel idLable6;
    private javax.swing.JLabel idLable7;
    private javax.swing.JLabel idLable8;
    private javax.swing.JLabel idLable9;
    private javax.swing.JTextField idTextField1;
    private javax.swing.JTextField idTextField10;
    private javax.swing.JTextField idTextField11;
    private javax.swing.JTextField idTextField3;
    private javax.swing.JTextField idTextField4;
    private javax.swing.JTextField idTextField5;
    private javax.swing.JTextField idTextField6;
    private javax.swing.JTextField idTextField7;
    private javax.swing.JTextField idTextField8;
    private javax.swing.JTextField idTextField9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JInternalFrame jInternalFrame7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField leghtTextField;
    private javax.swing.JLabel modelLable1;
    private javax.swing.JLabel modelLable2;
    private javax.swing.JLabel modelLable3;
    private javax.swing.JLabel modelLable4;
    private javax.swing.JLabel modelLable5;
    private javax.swing.JLabel modelLable6;
    private javax.swing.JLabel modelLable7;
    private javax.swing.JTextField modelTextField1;
    private javax.swing.JTextField modelTextField2;
    private javax.swing.JTextField modelTextField3;
    private javax.swing.JTextField modelTextField4;
    private javax.swing.JTextField modelTextField5;
    private javax.swing.JTextField modelTextField6;
    private javax.swing.JTextField modelTextField7;
    private javax.swing.JTextField productNameTextField1;
    private javax.swing.JTextField productNameTextField10;
    private javax.swing.JTextField productNameTextField11;
    private javax.swing.JTextField productNameTextField3;
    private javax.swing.JTextField productNameTextField4;
    private javax.swing.JTextField productNameTextField5;
    private javax.swing.JTextField productNameTextField6;
    private javax.swing.JTextField productNameTextField7;
    private javax.swing.JTextField productNameTextField8;
    private javax.swing.JTextField productNameTextField9;
    private javax.swing.JComboBox<String> productStatusComboBox;
    private javax.swing.JLabel rentLable;
    private javax.swing.JLabel rentLable1;
    private javax.swing.JLabel rentLable10;
    private javax.swing.JLabel rentLable11;
    private javax.swing.JLabel rentLable12;
    private javax.swing.JLabel rentLable13;
    private javax.swing.JLabel rentLable14;
    private javax.swing.JLabel rentLable15;
    private javax.swing.JLabel rentLable2;
    private javax.swing.JLabel rentLable3;
    private javax.swing.JLabel rentLable4;
    private javax.swing.JLabel rentLable5;
    private javax.swing.JLabel rentLable6;
    private javax.swing.JLabel rentLable7;
    private javax.swing.JLabel rentLable8;
    private javax.swing.JLabel rentLable9;
    private javax.swing.JTextField rentPerDayTextField1;
    private javax.swing.JTextField rentPerDayTextField2;
    private javax.swing.JTextField rentPerDayTextField3;
    private javax.swing.JTextField rentPerDayTextField4;
    private javax.swing.JTextField rentPerDayTextField5;
    private javax.swing.JTextField rentPerDayTextField6;
    private javax.swing.JTextField rentPerDayTextField7;
    private javax.swing.JTextField rentTextField;
    private javax.swing.JTextField serialTextField;
    private javax.swing.JTextField statusTextField1;
    private javax.swing.JTextField statusTextField2;
    private javax.swing.JTextField statusTextField3;
    private javax.swing.JTextField statusTextField4;
    private javax.swing.JTextField statusTextField5;
    private javax.swing.JTextField statusTextField6;
    private javax.swing.JTextField statusTextField7;
    private javax.swing.JTextField widthTextField;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
